"""added name_es_es field to categories

Revision ID: 4c1412b4690b
Revises: 9d701be6dad5
Create Date: 2024-11-04 09:42:51.296031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1412b4690b'
down_revision: Union[str, None] = '9d701be6dad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_es_es', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name_es_es')
    # ### end Alembic commands ###
