"""added img url to products

Revision ID: 637aa7affaea
Revises: 4c1412b4690b
Create Date: 2024-11-04 13:35:03.592608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637aa7affaea'
down_revision: Union[str, None] = '4c1412b4690b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('img_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'img_url')
    # ### end Alembic commands ###
