"""added identification field to entities

Revision ID: 7e518f541b42
Revises: 2de0f00a7686
Create Date: 2024-10-02 15:51:28.117933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e518f541b42'
down_revision: Union[str, None] = '2de0f00a7686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('identification', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'entities', ['identification'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entities', type_='unique')
    op.drop_column('entities', 'identification')
    # ### end Alembic commands ###
