"""nullable relations in purchase

Revision ID: b11eb7618746
Revises: aa88b398c146
Create Date: 2024-09-13 17:00:32.749274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11eb7618746'
down_revision: Union[str, None] = 'aa88b398c146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchases', 'establishment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchases', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchases', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchases', 'establishment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
