"""completed entity table, added entity purchase relation, unique constrain for product codes

Revision ID: d2d13b949f2e
Revises: e1506bab8483
Create Date: 2024-10-03 11:17:24.494725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d13b949f2e'
down_revision: Union[str, None] = 'e1506bab8483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('entities', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('entities', sa.Column('phone', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uix_format_code', 'product_codes', ['format', 'code'])
    op.add_column('purchases', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'entities', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'entity_id')
    op.drop_constraint('uix_format_code', 'product_codes', type_='unique')
    op.drop_column('entities', 'phone')
    op.drop_column('entities', 'address')
    op.drop_column('entities', 'email')
    # ### end Alembic commands ###
