"""updated constrains for NodeToken

Revision ID: ddaedc2d31b1
Revises: 38c8ba030e9e
Create Date: 2024-10-09 11:55:13.171163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddaedc2d31b1'
down_revision: Union[str, None] = '38c8ba030e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node_tokens', 'crawl_daily_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('node_tokens', 'can_view_receipt_images',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_node_tokens_name', table_name='node_tokens')
    op.create_index(op.f('ix_node_tokens_name'), 'node_tokens', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_tokens_name'), table_name='node_tokens')
    op.create_index('ix_node_tokens_name', 'node_tokens', ['name'], unique=False)
    op.alter_column('node_tokens', 'can_view_receipt_images',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('node_tokens', 'crawl_daily_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
