"""added product relation to purchase item

Revision ID: e1506bab8483
Revises: 7e518f541b42
Create Date: 2024-10-03 10:43:55.688419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1506bab8483'
down_revision: Union[str, None] = '7e518f541b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_column('purchase_items', 'product_id')
    # ### end Alembic commands ###
