"""node tokens table added

Revision ID: e7cf803e5f09
Revises: 0f877763f5ac
Create Date: 2024-10-04 16:36:24.069539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7cf803e5f09'
down_revision: Union[str, None] = '0f877763f5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_tokens_id'), 'node_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_node_tokens_key_hash'), 'node_tokens', ['key_hash'], unique=True)
    op.create_index(op.f('ix_node_tokens_name'), 'node_tokens', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_tokens_name'), table_name='node_tokens')
    op.drop_index(op.f('ix_node_tokens_key_hash'), table_name='node_tokens')
    op.drop_index(op.f('ix_node_tokens_id'), table_name='node_tokens')
    op.drop_table('node_tokens')
    # ### end Alembic commands ###
